version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: medusa-db-bz1aq
    volumes:
      - medusa-data:/var/lib/postgresql/data
    networks:
      - medusa-network

  medusa:
    build: .
    ports:
      - "9000:9000"
    environment:
      DATABASE_URL: postgres://postgres:admin@localhost:5432/medusa-db-bz1aq
    depends_on:
      - db
    networks:
      - medusa-network
    command: ["sh", "-c", "medusa migrations run && npm run start"]

volumes:
  medusa-data:

networks:
  medusa-network:
